/**
 * Pexels image manifest for backgrounds
 * Generated by scripts/fetch-pexels-images.js
 */

export const PEXELS_IMAGES = [
  { src: "/assets/pexels/pexels_7.jpeg", alt: "Wooden texture", use: "background" },
  { src: "/assets/pexels/pexels_8.jpeg", alt: "Wooden planks", use: "background" },
  { src: "/assets/pexels/pexels_1.jpeg", alt: "Healthcare professional at desk", use: "hero" },
  { src: "/assets/pexels/pexels_2.jpeg", alt: "Doctor with laptop", use: "hero" },
  { src: "/assets/pexels/pexels_5.jpeg", alt: "Senior consultation", use: "hero" },
  { src: "/assets/pexels/pexels_6.jpeg", alt: "Senior citizens", use: "hero" },
  { src: "/assets/pexels/pexels_9.jpeg", alt: "Insurance professional", use: "hero" },
  { src: "/assets/pexels/pexels_10.jpeg", alt: "Insurance policy", use: "hero" },
] as const;

export const WOODEN_BACKGROUNDS = [
  "/assets/pexels/pexels_7.jpeg",
  "/assets/pexels/pexels_8.jpeg",
];
